[book]
title = "Reform"
authors = ["Zicklag"]
description = "A unique programming language for letting you program with \"natural language\" DSLs."
language = "en"
src = "docs"

[build]
build-dir = "book"

[output.html]
default-theme = "Rust"
git-repository-url = "https://github.com/zicklag/reform/docs"
additional-css = ["theme/reform-highlight.css"]
additional-js = ["theme/reform-highlight.js"]

